HinoDeia2/grails-app/domain/hinodeia2/UsuarioRegra.groovy
package hinodeia2

import org.apache.commons.lang.builder.HashCodeBuilder

class UsuarioRegra implements Serializable {

	private static final long serialVersionUID = 1

	Usuario usuario
	Regra regra

	boolean equals(other) {
		if (!(other instanceof UsuarioRegra)) {
			return false
		}

		other.usuario?.id == usuario?.id &&
		other.regra?.id == regra?.id
	}

	int hashCode() {
		def builder = new HashCodeBuilder()
		if (usuario) builder.append(usuario.id)
		if (regra) builder.append(regra.id)
		builder.toHashCode()
	}

	static UsuarioRegra get(long usuarioId, long regraId) {
		UsuarioRegra.where {
			usuario == Usuario.load(usuarioId) &&
			regra == Regra.load(regraId)
		}.get()
	}

	static boolean exists(long usuarioId, long regraId) {
		UsuarioRegra.where {
			usuario == Usuario.load(usuarioId) &&
			regra == Regra.load(regraId)
		}.count() > 0
	}

	static UsuarioRegra create(Usuario usuario, Regra regra, boolean flush = false) {
		def instance = new UsuarioRegra(usuario: usuario, regra: regra)
		instance.save(flush: flush, insert: true)
		instance
	}

	static boolean remove(Usuario u, Regra r, boolean flush = false) {
		if (u == null || r == null) return false

		int rowCount = UsuarioRegra.where {
			usuario == Usuario.load(u.id) &&
			regra == Regra.load(r.id)
		}.deleteAll()

		if (flush) { UsuarioRegra.withSession { it.flush() } }

		rowCount > 0
	}

	static void removeAll(Usuario u, boolean flush = false) {
		if (u == null) return

		UsuarioRegra.where {
			usuario == Usuario.load(u.id)
		}.deleteAll()

		if (flush) { UsuarioRegra.withSession { it.flush() } }
	}

	static void removeAll(Regra r, boolean flush = false) {
		if (r == null) return

		UsuarioRegra.where {
			regra == Regra.load(r.id)
		}.deleteAll()

		if (flush) { UsuarioRegra.withSession { it.flush() } }
	}

	static constraints = {
		regra validator: { Regra r, UsuarioRegra ur ->
			if (ur.usuario == null) return
			boolean existing = false
			UsuarioRegra.withNewSession {
				existing = UsuarioRegra.exists(ur.usuario.id, r.id)
			}
			if (existing) {
				return 'userRole.exists'
			}
		}
	}

	static mapping = {
		id composite: ['regra', 'usuario']
		version false
	}
}

HinoDeia2/grails-app/controllers/hinodeia2/UsuarioRegraController.groovy
package hinodeia2



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class UsuarioRegraController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond UsuarioRegra.list(params), model:[usuarioRegraInstanceCount: UsuarioRegra.count()]
    }

    def show(UsuarioRegra usuarioRegraInstance) {
        respond usuarioRegraInstance
    }

    def create() {
        respond new UsuarioRegra(params)
    }

    @Transactional
    def save(UsuarioRegra usuarioRegraInstance) {
        if (usuarioRegraInstance == null) {
            notFound()
            return
        }

        if (usuarioRegraInstance.hasErrors()) {
            respond usuarioRegraInstance.errors, view:'create'
            return
        }

        usuarioRegraInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'usuarioRegra.label', default: 'UsuarioRegra'), usuarioRegraInstance.id])
                redirect usuarioRegraInstance
            }
            '*' { respond usuarioRegraInstance, [status: CREATED] }
        }
    }

    def edit(UsuarioRegra usuarioRegraInstance) {
        respond usuarioRegraInstance
    }

    @Transactional
    def update(UsuarioRegra usuarioRegraInstance) {
        if (usuarioRegraInstance == null) {
            notFound()
            return
        }

        if (usuarioRegraInstance.hasErrors()) {
            respond usuarioRegraInstance.errors, view:'edit'
            return
        }

        usuarioRegraInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'UsuarioRegra.label', default: 'UsuarioRegra'), usuarioRegraInstance.id])
                redirect usuarioRegraInstance
            }
            '*'{ respond usuarioRegraInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(UsuarioRegra usuarioRegraInstance) {

        if (usuarioRegraInstance == null) {
            notFound()
            return
        }

        usuarioRegraInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'UsuarioRegra.label', default: 'UsuarioRegra'), usuarioRegraInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'usuarioRegra.label', default: 'UsuarioRegra'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

HinoDeia2/grails-app/views/usuarioRegra/_form.gsp
<%@ page import="hinodeia2.UsuarioRegra" %>



<div class="fieldcontain ${hasErrors(bean: usuarioRegraInstance, field: 'regra', 'error')} required">
	<label for="regra">
		<g:message code="usuarioRegra.regra.label" default="Regra" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="regra" name="regra.id" from="${hinodeia2.Regra.list()}" optionKey="id" required="" value="${usuarioRegraInstance?.regra?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioRegraInstance, field: 'usuario', 'error')} required">
	<label for="usuario">
		<g:message code="usuarioRegra.usuario.label" default="Usuario" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="usuario" name="usuario.id" from="${hinodeia2.Usuario.list()}" optionKey="id" required="" value="${usuarioRegraInstance?.usuario?.id}" class="many-to-one"/>

</div>

HinoDeia2/grails-app/views/usuarioRegra/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'usuarioRegra.label', default: 'UsuarioRegra')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-usuarioRegra" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-usuarioRegra" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${usuarioRegraInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${usuarioRegraInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:usuarioRegraInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

HinoDeia2/grails-app/views/usuarioRegra/edit.gsp
<%@ page import="hinodeia2.UsuarioRegra" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'usuarioRegra.label', default: 'UsuarioRegra')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-usuarioRegra" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-usuarioRegra" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${usuarioRegraInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${usuarioRegraInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:usuarioRegraInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${usuarioRegraInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

HinoDeia2/grails-app/views/usuarioRegra/index.gsp
<%@ page import="hinodeia2.UsuarioRegra" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'usuarioRegra.label', default: 'UsuarioRegra')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-usuarioRegra" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-usuarioRegra" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="usuarioRegra.regra.label" default="Regra" /></th>
					
						<th><g:message code="usuarioRegra.usuario.label" default="Usuario" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${usuarioRegraInstanceList}" status="i" var="usuarioRegraInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${usuarioRegraInstance.id}">${fieldValue(bean: usuarioRegraInstance, field: "regra")}</g:link></td>
					
						<td>${fieldValue(bean: usuarioRegraInstance, field: "usuario")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${usuarioRegraInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

HinoDeia2/grails-app/views/usuarioRegra/show.gsp
<%@ page import="hinodeia2.UsuarioRegra" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'usuarioRegra.label', default: 'UsuarioRegra')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-usuarioRegra" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-usuarioRegra" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list usuarioRegra">
			
				<g:if test="${usuarioRegraInstance?.regra}">
				<li class="fieldcontain">
					<span id="regra-label" class="property-label"><g:message code="usuarioRegra.regra.label" default="Regra" /></span>
					
						<span class="property-value" aria-labelledby="regra-label"><g:link controller="regra" action="show" id="${usuarioRegraInstance?.regra?.id}">${usuarioRegraInstance?.regra?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${usuarioRegraInstance?.usuario}">
				<li class="fieldcontain">
					<span id="usuario-label" class="property-label"><g:message code="usuarioRegra.usuario.label" default="Usuario" /></span>
					
						<span class="property-value" aria-labelledby="usuario-label"><g:link controller="usuario" action="show" id="${usuarioRegraInstance?.usuario?.id}">${usuarioRegraInstance?.usuario?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:usuarioRegraInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${usuarioRegraInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>